---
:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: :all
  :test_file_prefix: test_
  :build_root: build/test

:plugins:
  :enabled:
    - gcov

:paths:
  :test:
    - test/unit
  :source:
    - SensorECU/Core/Src
    - Bootloader/Core/Src
  :include:
    - test/support
    - SensorECU/Core/Inc
    - Bootloader/Core/Inc
  :support:
    - test/support

:defines:
  :common:
    - UNIT_TEST
  :gcov:
    - UNIT_TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback

:flags:
  :test:
    :compile:
      :*:
        - -std=c99
        - -Wall
        - -Wno-unused-parameter
        - -DUNIT_TEST
  :gcov:
    :compile:
      - -std=c99
      - -Wall
      - -Wno-unused-parameter
      - -DUNIT_TEST

